config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true, length: {maximum:50}
    validates :phone, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }

    has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private
        def require_logged_in_user
            unless user_signed_in?
                flash[:danger] = 'Área restrita. favor realizar login'
                redirect_to entrar_path
            end
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to contacts_path
    else
      flash.now[:danger] = 'Email ou senha inválidos'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:sucess] = 'Logout com sucesso'
    redirect_to entrar_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
        @nome = "Gustavo"        
    end
    def sobre        
    end
    def contato        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in_user, only:[:edit, :update]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:sucess] = 'Usuário cadastrado com sucesso'
            redirect_to root_url
        else
            render 'new'
        end
    end
    def update
        if current_user.update(user_params)
            flash[:sucess] = 'Dados atualizados'
            redirect_to contacts_path
        else
            render edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>

app/views/contacts/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editar Contato</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for [current_user, @contact] do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Atualizar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Meus Contatos</h1>
  </div>

  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Telefone</th>
          <th colspan="2">
            Ações
            <%= link_to 'Novo Contato', new_contact_path(current_user), class: 'btn btn-success' %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @contacts.empty? %>
          <tr>
            <td colspan="4" class="text-center">
              <h3>Sem contatos cadastrados.</h3>
              <%= link_to 'click aqui', new_contact_path(current_user) %> para cadastrar um novo contato
            </td>
          </tr>
        <% end %>
        <% @contacts.each do |c| %>
        <tr>
          <td>
            <%= c.name %>
          </td>
          <td>
            <%= c.phone %>
          </td>
          <td>
            <%= link_to 'Editar', edit_user_contact_path(current_user, c), class: 'btn btn-warning' %>
          </td>
          <td>
            <%= link_to 'Excluir', user_contact_path(current_user, c), method: :delete, class: 'btn btn-danger', data: { confirm: 'Tem certeza que deseja excluir?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Adicionar Novo Contato</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for [current_user, @contact] do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %> 
      </li>
      <li>
        <%= link_to 'Contato', contato_path  %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu"
                aria-expanded=" false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
        </div>

        <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
        <div class="collapse navbar-collapse" id="expanded-menu">
            <ul class="nav navbar-nav">
                <% if !user_signed_in? %>
                <li class="active">
                    <%= link_to 'Nova Conta', new_user_path %>
                    <!--cadastro_path -->
                </li>
                <% end %>
            </ul>

            <ul class="nav navbar-nav navbar-right">

                <% if !user_signed_in? %>
                <li>
                    <%= link_to 'Entrar', entrar_path  %>
                    <!--entrar_path-->
                </li>
                <% else %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">
                        bem vindo, <%= current_user.name %> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to 'Minha Pagina', contacts_path %>
                        </li>
                        <li>
                            <%= link_to 'Editar', edit_user_path(current_user) %>
                        </li>
                        <li class="divider" role="separator"></li>
                        <li>
                            <%= link_to 'Sair', sair_path, method: :delete %>
                        </li>
                    </ul>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>

    <div class="container">

    <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      <% end %>
    <% end %>

    <%= yield %>
    </div>
  </body>

  <footer>
  <%= render 'layouts/footer'%>
  </footer>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href="http://www.twitter.com/brunojppb">@brunojppb</a> para saber mais.
</p>

app/views/static_pages/index.html.erb
<div class="container">
  <div>
    <div class="row">
      <div class="col-lg-8">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="https://placehold.it/800x400?text=IMAGE" alt="Image">
              <div class="carousel-caption">
                <h3>Sell $</h3>
                <p>Money Money.</p>
              </div>
            </div>
            <div class="item">
              <img src="https://placehold.it/800x400?text=Another Image Maybe" alt="Image">
              <div class="carousel-caption">
                <h3>More Sell $</h3>
                <p>Lorem ipsum...</p>
              </div>
            </div>
          </div>
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="container col-lg-3">
        <div>
          <h1>Lorem ipsum</h1>
          <p>
            Ullamco mollit aliqua officia sunt consequat officia. Consequat culpa dolor 
            adipisicing deserunt eiusmod cillum. Amet mollit esse irure anim cupidatat irure qui minim qui
            tempor excepteur amet mollit ea. Laborum magna nisi sint laboris qui. Qui irure magna id dolore dolor
            proident fugiat nulla ut. Tempor cupidatat dolore exercitation cupidatat. Quis id elit ea ad enim laborum 
            quis ad magna pariatur.
          </p>
        </div>
      </div>
      <div class="container col-lg-12 mt-20">
        <div class="jumbotron col-lg-12">
          <div class="al-l col-lg-6">
            <h1>Contact List</h1>
            <p>
              Gerencie seus contatos em qualquer lugar!
            </p>
          </div>
          <div class="al-r col-lg-6">
            <h3>É novo no site?</h3>
            <p>
              <%= link_to 'Crie Sua Conta', new_user_path, class: 'btn btn-primary btn-md' %>
            </p>
            <h3>Já tem cadastro?</h3>
            <p>
              <%= link_to 'Entrar', entrar_path, class: 'btn btn-primary btn-md' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
  Criado com o intuito de ensinar um pouco sobre o Framework Ruby on Rails, Contact List mostrará como aprender as peças que formam essa ferramenta
  tão poderosa.
</p>

app/views/users/_form.html.erb
<%= render 'layouts/error_messages', object: f.object%>
    <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="form-group">
        <%= f.label :email%>
        <%= f.text_field :email, class: 'form-control'%>
    </div>

    <div class="form-group">
        <%= f.label :password%>
        <%= f.password_field :password, class: 'form-control', id: 'user_password'%>
    </div>
    
    <div class="form-group">
        <%= f.label :password_confirmation%>
        <%= f.password_field :password, class: 'form-control', id: 'user_password_confirmation'%>
    </div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editar dados</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for current_user do |f| %>
      <%= render 'form', f: f%>
      <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Cadastra-se</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @user do |f| %>
      <%= render 'form', f: f%>
      <%= f.submit 'Cadastrar', class: 'btn btn-primary', id: 'register' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2>Olá, <%= current_user.name%></h2>